site_name: My Notes
nav:
    - Home: index.md
    - Backup: backup/backup-notes.md
    - CLI: cli/cli-notes.md
    - Containers: containers/container-notes.md
    - DNS:
        - Overview: dns/dns-notes.md
        - Configs:
            - blocky-config.yml: dns/configs/blocky-config.yml
            - unbound.conf: dns/configs/unbound.conf
    - Git: git/git-notes.md
    - Network:
        - Overview: network/networking-notes.md
        - Cisco: network/cisco-notes.md
        - Configs:
            - interfaces: network/configs/interfaces
            - nftables.conf: network/configs/nftables.conf
    - Sysadmin:
        - Overview: sysadmin/sysadmin-notes.md
        - Databases: sysadmin/databases-notes.md
        - ERPNext: sysadmin/erpnext-notes.md
        - WordPress: sysadmin/wordpress-notes.md
        - SELinux: sysadmin/selinux-notes.md
        - CoreOS:
            - Fedora coreOS: sysadmin/fedora-coreos/fedora-coreos-notes.md
            - basic.bu: sysadmin/fedora-coreos/basic.bu
        - Systemd Examples:
            - app.service: sysadmin/systemd_examples/app.service
            - freedns.service: sysadmin/systemd_examples/freedns.service
            - freedns.timer: sysadmin/systemd_examples/freedns.timer
            - rclone.service: sysadmin/systemd_examples/rclone.service
        - Configs:
            - sshd_config: sysadmin/configs/sshd_config
        - Scripts:
            - wg-gen.sh: sysadmin/scripts/wg-gen.sh
    - Virtual Machine: virtual-machine/virtual-machine-notes.md
    - Web: web/web-server-notes.md
theme: readthedocs
